### ISSUE TITLE
parralel test failing for 3.6.0

### ISSUE THREAD

**Issue by oliviermattelaer** [mg5amcnlo/mg5amcnlo#129]
Hi @marcozaro,

the following script (which is one of the parralel test)
```
import model MSSM_SLHA2
generate p p > go go [real=QCD]
output
launch NLO -f
```
is crashing for the branch 3.6.0

The issue seems to be sudakov related:
```
ewsudakov_functions.f:1829:25:

 1829 |       dGmudalpha=  MDL_GF*aewm1
      |                         1
Error: Symbol ‘mdl_gf’ at (1) has no IMPLICIT type; did you mean ‘mdl_gw’?
make: *** [ewsudakov_functions.o] Error 1
```

I guess that the Sudakov is not supporting that model, but could we have something such that it does still compile?

**Comment by marcozaro** [comment]
Ciao Olivier,
this should do the job, hopefully

a7a8634

Marco

**Comment by oliviermattelaer** [comment]
Perfect,

Thanks,

Olivier
