### ISSUE TITLE
pdfwrap_lhapdf does not compile at NLO in 3.6.0

### ISSUE THREAD

**Issue by marcozaro** [mg5amcnlo/mg5amcnlo#157]
Ciao Olivier,
If I use 3.6.0 from LP, generate any process at NLO
generate p p > t t~ [QCD] ; output ; launch
set pdlabel lhapdf

then it crashes at compilation with the error
	    gfortran -O -fno-automatic -ffixed-line-length-132  -c -o pdfwrap_lhapdf.o pdfwrap_lhapdf.f
	    pdfwrap_lhapdf.f:8: Error: Can't open included file '../vector.inc'
	    make[1]: *** [pdfwrap_lhapdf.o] Error 1
	    make: *** [../lib/libpdf.a] Error 2

I solved this error by removing that line inside pdfwrap_lhapdf.f in the output dir.
Shall we remove it also from the template file (madgraph/iolibs/template_files/pdf_wrap_lhapdf.f)?  Will this have effects on LO?

Thanks!
Cheers

Marco

**Comment by oliviermattelaer** [comment]
Ok will look at this before I release 3.6.1. I guess that I will need a ifdef in the template.

Thanks (and sorry for the delay)

Olivier

**Comment by oliviermattelaer** [comment]
Thanks @marcozaro  this is fixed in the latest push of 3.6.1:
https://github.com/mg5amcnlo/mg5amcnlo/commit/37557db6b45f5d5109d851f64b05dc3efc65d42a
