### ISSUE TITLE
Server Update 

### ISSUE THREAD

**Issue by oliviermattelaer** [mg5amcnlo/mg5amcnlo#16]
# Milan
- [x] HTML update (bzr)
- [x] model database (following git)
- [x] HepToolsInstaller (following git)
- [x] ExRootAnalysis (following git)
- [x] auto-update server (following bzr version: 2.0-git)
    - [ ] to update to git?
- [x] maddm (following bzr)
- [x] maddump (folowing bzr)
- [x] MadSTR (following bzr)
- [x] MG5_PY8_int (following git)
- [x] PPPC4DMID (bzr)
- [x] HTTPS

# vmadgraph (new louvain)

- [x] HTML update (bzr)
- [x] model database (following git)
- [x] HepToolsInstaller (following git)
- [x] ExRootAnalysis (following git)
- [x] auto-update server (following bzr version: 3.0)
   - [x] to update to 3.0_git 
   - [ ] to update to git? 
- [x] maddm (following bzr)
- [x] maddump (folowing bzr)
- [x] MadSTR (following bzr)
- [x] MG5_PY8_int (following git)
- [x] PPPC4DMID (bzr)
- [x] pare-feux ouvert (130.104.1.343)
- [x] basculement de DNS
    - [x]  demande (a cp3)
    - [x] basculement de DNS demande  au SRI
    - [x] basculement de DNS effectif

# UIUC (going to disapear)
- [x] full redirection towards milan
- [x] decomissioning

**Comment by kratsg** [comment]
So it looks like UIUC is going away (/cc @msneubauer @matthewfeickert @mhance). Do you know what happens to all of the tarballs of the old versions? I can't seem to find them right now and I suspect that's part of the server maintenance mentioned here, but any ETA on when they will reappear if at all? Currently a blocker for our CI in [mapyde](https://github.com/scipp-atlas/mario-mapyde) that we use to build a couple of docker images.

**Comment by matthewfeickert** [comment]
@kratsg I don't have any good advice for you here unfortunately as the Docker images I've been building have used the [`http://madgraph.phys.ucl.ac.be` mirrors to pull down the `MG5aMC_PY8_interface`](https://github.com/scailfin/MadGraph5_aMC-NLO/blob/42048995fc90a58eec450f4dda999a8d4f65670d/docker/debian/Dockerfile#L126-L149).

I've only used the Illinois mirror for publicly viewing in my web browser given that it seems the MadGraph mirrors don't share public viewing permissions across mirrors.

Can you share what components from the Illinois mirror were critical that you can't get from the other mirrors?

**Comment by kratsg** [comment]
The launchpad doesn't really contain all the tarballs necessary. For example, for `2.6.3.2`, this URL used to work: http://madgraph.physics.illinois.edu/Downloads/MG5_aMC_v2.6.3.2.tar.gz -- but now I can't find this tarball anywhere.

**Comment by oliviermattelaer** [comment]
> So it looks like UIUC is going away

I have indeed set uiuc in redirecting mode trough our new milan server and uiuc will be decomissioned in a couple of months (so at that time no-redirection will be in place anymore creating potential issue for old version of MG5aMC which will still do request to that server).

> The launchpad doesn't really contain all the tarballs necessary. For example, for `2.6.3.2`, this URL used to work: http://madgraph.physics.illinois.edu/Downloads/MG5_aMC_v2.6.3.2.tar.gz -- but now I can't find this tarball anywhere.

2.6.3.2 should not be used any more it is so/too old. It also had 4 debug version (i.e. the last bug fix for 2.6 feature is  2.6.7) and the tarball of 2.6.7 is available on launchpad (still extremelly old but already much better than 2.6.3.2).
I would strongly suggest to use tarball of the LTS version (currently 2.9.x). Those tarball will stay on launchpad forever (but I also suggest to keep up with the last digit of the LTS since they correspond to bug fixing).

**Comment by kratsg** [comment]
> 2.6.3.2 should not be used any more it is so/too old. It also had 4 debug version (i.e. the last bug fix for 2.6 feature is 2.6.7) and the tarball of 2.6.7 is available on launchpad (still extremelly old but already much better than 2.6.3.2).

We need to have access to versions like these for exact reproducibility of published papers. Can we have the tarballs back instead of being removed? We're not using 2.6.3.2 for active work but it *is* used for verifying/checking prior results. The tarball did exist. Why can't it just continue to exist?

**Comment by oliviermattelaer** [comment]
You have all version2 version tag in bazaar here:
https://code.launchpad.net/~madteam/mg5amcnlo/series2.0
and for version3:
https://code.launchpad.net/~madteam/mg5amcnlo/3.x

**Comment by matthewfeickert** [comment]
> You have all version2 version tag in bazaar here: https://code.launchpad.net/~madteam/mg5amcnlo/series2.0

Where is the public tag information / how do you access this from a public API?

Unless I'm (hopefully) wrong `bzr` can't do things like provide tag information in the version control information

https://stackoverflow.com/questions/15024597/how-to-download-a-bazaar-repository-with-revision-history-without-using-the-bzr

Poking around https://bazaar.launchpad.net/~madteam/mg5amcnlo/series2.0/changes and assuming "pass to 2.6.3.2" means "this is the commit for v2.6.3.2" then I think(?) [revision 279](https://bazaar.launchpad.net/~madteam/mg5amcnlo/series2.0/revision/279) is the correct revision.

There's no tarball available as the "download tarball" link is broken so attempting to access this with `bzr`

```console
$ bzr branch lp:mg5amcnlo/2.0
$ cd 2.0
$ bzr update -r279
$ cat VERSION 
version = 2.6.3.2
date = 2018-06-22








```

So I guess this is the recommended workflow.

**Comment by oliviermattelaer** [comment]
Looks like the last update of the launchpad website, broke the "download tarball". So yes for the moment, one is force to use bzr.
With that version, you can then you can create the official tarball via the command:
```
./bin/create_release.py
```
(and likely accept all the warning that it will raise, including(?) the de-activation of the auto-update feature)

**Comment by kratsg** [comment]
Note: a lot of people (myself included) relied on something like this

```
http://madgraph.physics.illinois.edu/Downloads/MG5_aMC_v${MG_VERSION}.tar.gz
```

and this is a pretty silent breaking change that should be noisier to let others know.

**Comment by kratsg** [comment]
(Also, I'm sure CERN would be happy to host all the tarballs until the eventual heat death of the universe...)

**Comment by matthewfeickert** [comment]
So I've done the following 

```console
$ docker pull python:2.7
$ docker run --rm -ti python:2.7 /bin/bash
root@2b3fbea79846:~# cat /requirements.txt 
epydoc==3.0.1
matplotlib==2.2.5
six==1.14.0
root@2b3fbea79846:~# apt update && \
apt install -y bzr && \
python -m pip install --upgrade pip setuptools wheel && \
python -m pip install --requirement /requirements.txt
bzr branch lp:mg5amcnlo/2.0 && \
cd 2.0 && \
bzr update -r279 && \
./bin/create_release.py
Updated to revision 279 of branch /2.0

version = 2.6.3.2

WARNING: The release time information is : date = 2018-06-22

Do you want to continue anyway? (y/n)y
find 304 for the revision number -> starting point for the auto-update
version on the web is 971
CRITICAL: current version on the web is 971
This FORBIDS any auto-update for this version.
Do you want to continue anyway? (y/n)y
Branching /2.0 to directory MG5_aMC_v2_6_3_2
Branched 304 revisions.                                                                                                                                                               
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| In /2.0/MG5_aMC_v2_6_3_2/madgraph/various/plot_djrs.py:
| Import failed (but source code parsing was successful).
|     Error: IOError: [Errno 2] No such file or directory: './Events/run_01/tag_1_djrs.dat' (line 66)
|   
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| In /2.0/MG5_aMC_v2_6_3_2/madgraph/madevent/hel_recycle.py:
| Import failed (but source code parsing was successful).
|     Error: SyntaxError: invalid syntax (hel_recycle.py, line 91)
|   
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| In /2.0/MG5_aMC_v2_6_3_2/aloha/aloha_parsers.py:
| Source code parsing failed (but introspection was successful).
|     Error: Error during parsing: invalid syntax (/2.0/MG5_aMC_v2_6_3_2/aloha/aloha_parsers.py, line 37) -- Bad dotted name
|   
Warning: No information available for madgraph.madweight.mod_file.TestMod_file's base unittest.TestCase
Warning: No information available for madgraph.madweight.mod_file.TestMod_file's base unittest.TestCase
Warning: 88 markup errors were found while processing docstrings.  Use the verbose switch (-v) to display markup errors.
mkdir: created directory 'download-temp'
You have not informed bzr of your Launchpad ID, and you must do this to
write to Launchpad or access private data.  See "bzr help launchpad-login".
Branched 167 revisions.                                                                                                                                                               
--2022-07-15 16:11:31--  http://collier.hepforge.org/collier-latest.tar.gz
Resolving collier.hepforge.org (collier.hepforge.org)... 129.234.186.186
Connecting to collier.hepforge.org (collier.hepforge.org)|129.234.186.186|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://collier.hepforge.org/collier-latest.tar.gz [following]
--2022-07-15 16:11:32--  https://collier.hepforge.org/collier-latest.tar.gz
Connecting to collier.hepforge.org (collier.hepforge.org)|129.234.186.186|:443... connected.
ERROR: The certificate of ‘collier.hepforge.org’ is not trusted.
ERROR: The certificate of ‘collier.hepforge.org’ has expired.
--2022-07-15 16:11:32--  https://bitbucket.org/peraro/ninja/downloads/ninja-latest.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22c0:3470, 2406:da00:ff00::22cd:e0db, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-15 16:11:33 ERROR 404: Not Found.

Create the tar file MG5_aMC_v2.6.3.2.tar.gz
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
Running tests on directory MG5_aMC_v2_6_3_2
['INSTALL', 'doc.tgz', 'PLUGIN', 'doc', 'models', 'madgraph', 'HELAS', 'vendor', '.bzrignore', 'MadSpin', 'LICENSE', 'README', 'proc_card.dat', 'tests', 'UpdateNotes.txt', 'bin', 'input', 'aloha', 'Template', 'mg5decay', 'VERSION']
Traceback (most recent call last):
  File "tests/test_manager.py", line 60, in <module>
    import six
ModuleNotFoundError: No module named 'six'
status: 1
Traceback (most recent call last):
  File "tests/test_manager.py", line 60, in <module>
    import six
ModuleNotFoundError: No module named 'six'
status: 1
Traceback (most recent call last):
  File "tests/test_manager.py", line 60, in <module>
    import six
ModuleNotFoundError: No module named 'six'
status: 1
Thanks for creating a release. please check that the tests were sucessfull before releasing the version
```

I've uploaded it (temporarily &mdash; I will remove this section of this comment once I remove it later) to my CERN Box and it is public at this URL: https://feickert.web.cern.ch/feickert/tmp/MG5_aMC_v2.6.3.2.tar.gz

@kratsg Can you run a workflow with

```console
curl -sLO https://feickert.web.cern.ch/feickert/tmp/MG5_aMC_v2.6.3.2.tar.gz
```
and let me know if the release I made is valid?

**Comment by oliviermattelaer** [comment]
The atlas repo does actually have evem more MG5 tarball that the amount that was on the uiuc server. 
I will try next week to transfer the v2.6.3.2 tarball from the uiuc server to the milan one (so the old link should be back working but only for a couple of month).

**Comment by kratsg** [comment]
> I can discuss that point at our next mg developer meeting (in September). But for the moment, I will keep the strategy that only LTS version are staying forever on launchpad. plus the latest debug version of any feature release.

Fair, but this does mean that we end up publishing papers with very-hard-to-grab (old) MadGraph releases that are not necessarily LTS. I don't think any collaboration like ATLAS or CMS have a policy to only use LTS releases...

**Comment by oliviermattelaer** [comment]
uiuc server is currently down (also the ssh server) so I'm not able to transfer any of the old tar for the moment. 
Let's see if the server goes back online  by itself (they might have a maintenance or something similar) otherwise I will have to ask my local contact to contact their IT team to see if they can do something.

**Comment by oliviermattelaer** [comment]
I got some information on the uiuc server. 
A power outage occured on friday and the system hosting our virtual machine/webise decided to fully re-install itself.
In principle, they have backup of all data. But I guess that service will not be back online before next week at best.

**Comment by oliviermattelaer** [comment]
The tarball for 2.6.3.2 is now back accessible trough uiuc old web adress (via a redirection trough our new milan server)
