### ISSUE TITLE
http://madgraph.phys.ucl.ac.be/ gives 403 Forbidden

### ISSUE THREAD

**Issue by matthewfeickert** [mg5amcnlo/mg5amcnlo#21]
At the time of posting, http://madgraph.phys.ucl.ac.be/ results in a 403 error with

```
Forbidden

You don't have permission to access / on this server.
```

This means that at the moment all public facing generation links on the LaunchPad landing page (https://launchpad.net/mg5amcnlo) are broken as:

> LO generation can also be done directly online at: http://madgraph.phys.ucl.ac.be/ or http://madgraph.hep.uiuc.edu/

either results in the above 403 or are down given the reasons discussed in Issue #16 (it would be helpful to have all links previous Illinois links removed in general).

This also means that files hosted at URLs like `http://madgraph.phys.ucl.ac.be/Downloads/MG5aMC_PY8_interface/MG5aMC_PY8_interface_V1.3.tar.gz` are now inaccessible.

Is this a planned movement of hosting and resources? If so, what is the preferred location now?

**Comment by oliviermattelaer** [comment]
Looks like I miss the notification from this issue. 
So http://madgraph.phys.ucl.ac.be/ is back online.

Concerning http://madgraph.hep.uiuc.edu/ it should be redirecting towards https://madgraph.mi.infn.it//
but indeed this seems to sometimes work and sometimes not. 
Removing all reference to http://madgraph.hep.uiuc.edu/ are in progress.

Olivier

**Comment by matthewfeickert** [comment]
Many thanks @oliviermattelaer!
