### ISSUE TITLE
wrong coefficients in runmass function

### ISSUE THREAD

**Issue by marcozaro** [mg5amcnlo/mg5amcnlo#29]
https://github.com/mg5amcnlo/mg5amcnlo/blob/57eea3e92d06d2fb27cd3c0e66ced15ed2d05a44/Template/NLO/SubProcesses/reweight_xsec.f#L425

The coefficients (lines 425-426) should be 1/6d0 1/3d0 and 1/2d0

I am checking the numeric effect

**Comment by marcozaro** [comment]
effects seem to be minor (within integration uncertainties, at the permil level), both on central value and uncertainties

**Comment by oliviermattelaer** [comment]
Hi Marco,

I guess that we can close this now? If not please re-open it

Olivier

**Comment by marcozaro** [comment]
perfect , thanks

marco
