### ISSUE TITLE
Problems with root files generated by MG5

### ISSUE THREAD

**Issue by Carlesmer** [mg5amcnlo/mg5amcnlo#38]
Hi everyone. I have a problem in the root files generated directly by madgraph, and with the root output file generated by delphes as well:

Warning in <TClass::Init>: no dictionary for class LHEFEvent is available
Warning in <TClass::Init>: no dictionary for class Event is available
Warning in <TClass::Init>: no dictionary for class LHEFWeight is available
Warning in <TClass::Init>: no dictionary for class GenParticle is available
Warning in <TClass::Init>: no dictionary for class SortableObject is available
Warning in <TClass::Init>: no dictionary for class Track is available
Warning in <TClass::Init>: no dictionary for class Tower is available
Warning in <TClass::Init>: no dictionary for class Jet is available
Warning in <TClass::Init>: no dictionary for class MissingET is available
Warning in <TClass::Init>: no dictionary for class Electron is available
Warning in <TClass::Init>: no dictionary for class Photon is available
Warning in <TClass::Init>: no dictionary for class Muon is available
Warning in <TClass::Init>: no dictionary for class ScalarHT is available
(TFile *) 0x55b4626d38d0

Thank you.

**Comment by oliviermattelaer** [comment]
Hi,

MG5aMC does not generate any rootfile.
So I guess that you refer either to ExRootanalysis or to Delphes (or to some other third party tools)
Both ExRootanalysis and Delphes have the same technology for the reading/writing root files, (they have one author in common) so it would make sense.

I have personally (and the full MG5aMC team as a whole) no expertise in such format and furthemore no expertise in those tools, so the only suggestion that I have is to contact the authors of those tools directly (Delphes should have a ticketing system)

Cheers,

Olivier
