### ISSUE TITLE
making .lhe files for prompt photon processes

### ISSUE THREAD

**Issue by RaseebHaroon** [mg5amcnlo/mg5amcnlo#39]
Ubuntu: 22.04.1LTS
MG5     :  3.4.2
I was trying to run the following processes,
• qg → qγ
• qq~ → gγ
• gg → gγ
• qq~ → γγ
• gg → γγ

and I am having trouble, either it doesn't recognize q, or doesn't run a process like g g > g a. I need to shower these in stand-alone Pythia. I am new to madgraph and any help would be appreciated.

Error: MG5_aMC>generate g g > g a
INFO: Checking for minimal orders which gives processes. 
INFO: Please specify coupling orders to bypass this step. 
INFO: Trying coupling order WEIGHTED<=3: WEIGTHED IS QCD+2*QED 
INFO: Trying process: g g > g a WEIGHTED<=4 @1  
Command "generate g g > g a" interrupted with error:
NoDiagramException : No amplitudes generated from process Process: g g > g a WEIGHTED=4 @1. Please enter a valid process

**Comment by oliviermattelaer** [comment]
Hi,

We do not have a default meaning for "q", we do have one for "j" (all massless quark of the model) and for "p" (same definition as "j")

You can use the commands like
define q = u d s c
define q~ = u~ d~ s~ c~
to define the content of the q and q~ label as you want.

Concerning g g > g a or g g > a a, those are loop-induced process.
For that I would refer you to the loop induced paper for details:
[1507.00020] [hep-ph] (https://arxiv.org/abs/1507.00020)

Note that you have to do two separate computation for the loop induced process and the tree-level process.

Cheers,

Olivier

**Comment by RaseebHaroon** [comment]
Thank you for your quick reply, it was quite heplful.
