### ISSUE TITLE
Pythia8 interface crash

### ISSUE THREAD

**Issue by sihyunjeon** [mg5amcnlo/mg5amcnlo#55]
Hi Olivier,

I get a crash when I do

`import model loop_sm-no_b_mass`
`generate p p > t z j`
`add process p p > t z j j`

and run pythia8 with jet MLM merging (Segmentation fault when running run_PY8.sh)

I used v2.9.15.

**Comment by sihyunjeon** [comment]
Running process separately seems to work so something is not working with MLM, would there be any reason?

**Comment by oliviermattelaer** [comment]
So the crash is within PY8?

If yes, I'm worried that I can not really help....

Olivier

On 17 May 2023, at 20:24, Sihyun Jeon ***@***.***> wrote:



Running process separately seems to work so something is not working with MLM, would there be any reason?

**Comment by sihyunjeon** [comment]
hmmm so regarding MLM merging, there is no reason for this to crash due to MadGraph related issue right?
i was wondering if I was trying to use MLM merging for a process that doesn't work with MLM

**Comment by sihyunjeon** [comment]
https://gitlab.com/Pythia8/releases/-/issues/295

Hi olivier I posted here, keeping notes,
thanks!

**Comment by sihyunjeon** [comment]
@oliviermattelaer 
Hi Olivier,

I just checked with standalone pythia and it seems that pythia8306 is not taking lhe.gz as an input when doing mlm showering.
So it's either two things.
1. madgraph compresses lhe files earlier than it used to do
2. pythia at some point stopped taking lhe.gz files as an input

I am guessing 2. since as I report in [1], their main89.cc which is mlm command module does not work. Their example is given with lhe.gz file - this doesn't work, if i unzip it, it works. So I think this never went through their unit test

[1] https://gitlab.com/Pythia8/releases/-/issues/295

**Comment by oliviermattelaer** [comment]
Pythia was/(is?) supported zipped file, you have to configure pythia to made it work though.

Olivier

On 28 May 2023, at 14:01, Sihyun Jeon ***@***.***> wrote:



@oliviermattelaer<https://github.com/oliviermattelaer>
Hi Olivier,

I just checked with standalone pythia and it seems that pythia8306 is not taking lhe.gz as an input when doing mlm showering.
So it's either two things.

  1.  madgraph compresses lhe files earlier than it used to do
  2.  pythia at some point stopped taking lhe.gz files as an input

I am guessing 2. since as I report in [1], their main89.cc which is mlm command module does not work. Their example is given with lhe.gz file - this doesn't work, if i unzip it, it works. So I think this never went through their unit test

[1] https://gitlab.com/Pythia8/releases/-/issues/295

**Comment by sihyunjeon** [comment]
Hi so I tried that and it works with standalone pythia. So I am now thinking something doesn't work from madgraph side

**Comment by sihyunjeon** [comment]
Hey

Beams:setProductionScalesFromLHEF=on

This seems to be the problematic spot. If I remove this from the PY8card it works

**Comment by sihyunjeon** [comment]
import model sm-no_b_mass
generate p p > t z j
add process p p > t z j j
launch
shower=PYTHIA8
0
set nevents 10
set no_parton_cut
set xqcut 20
set mpi off
set use_syst False

This is to keep note - i am sometimes seeing and sometimes not seeing problems... let me investigate more

**Comment by sihyunjeon** [comment]
Ok so, with the restriction card at the bottom + SM model file, it fails in the shower.

import model sm-ckm_no_b_mass
generate p p > t z j
add process p p > t z j j
launch
shower=PYTHIA8
0
set nevents 10
set no_parton_cut
set xqcut 20
set mpi off
set use_syst False

However, if I remove `Beams:setProductionScalesFromLHEF=on` in the PY8 card and run, it works fine. is there a reason for this? Other model restriction cards work fine without having any issues, I tested with 'sm-ckm', 'sm-no_b_mass'.


######################################################################
## PARAM_CARD AUTOMATICALY GENERATED BY THE UFO #####################
######################################################################

###################################
## INFORMATION FOR SMINPUTS
###################################
Block SMINPUTS
 1 1.325070e+02 # aEWM1
 2 1.166390e-05 # Gf
 3 1.180000e-01 # aS

###################################
## INFORMATION FOR MASS
###################################
Block MASS
 4 0.000000e+00 # MC
 5 0.000000e+00 # MB
 6 1.730000e+02 # MT
 11 0.000000e+00 # Me
 13 0.000000e+00 # MM
 15 1.777000e+00 # MTA
 23 9.118800e+01 # MZ
 25 1.250000e+02 # MH

###################################
## INFORMATION FOR DECAY
###################################
DECAY 6 1.491500E+00
DECAY 15 2.270000e-12
DECAY 23 2.441404e+00
DECAY 24 2.047600e+00
DECAY 25 6.38233934e-03

###################################
## INFORMATION FOR WOLFENSTEIN
###################################
Block Wolfenstein
 1 2.253000e-01 # lamWS
 2 8.080000e-01 # AWS
 3 1.320000e-01 # rhoWS
 4 3.410000e-01 # etaWS

###################################
## INFORMATION FOR YUKAWA
###################################
Block YUKAWA
 4 0.000000e+00 # ymc
 5 0.000000e+00 # ymb
 6 1.730000e+02 # ymt
 11 0.000000e+00 # yme
 13 0.000000e+00 # ymm
 15 1.777000e+00 # ymtau

**Comment by sihyunjeon** [comment]
setProductionScalesFromLHEF so this is the problem. but strangely it works fine with pythia8 standalone main89 while having "setProductionScalesFromLHEF = on" in the pythia card.
