### ISSUE TITLE
Initialization of JAMP

### ISSUE THREAD

**Issue by claudioseveri** [mg5amcnlo/mg5amcnlo#72]
Hello everyone,

In NLO runs the JAMP matrix in born.f is not all always filled at each call.
This is very common, see for example tt~ production:
`C         JAMPs contributing to orders QCD=2 QED=0`
`          JAMP(1,1) = (1.666666666666667D-01)*AMP(2)`
`          JAMP(2,1) = (-5.000000000000000D-01)*AMP(2)`
`C         JAMPs contributing to orders QCD=0 QED=2`
`          JAMP(1,2) = (-1.000000000000000D+00)*AMP(1)+(-1.000000000000000D+00)*AMP(3)`
the value of JAMP(2,2), which is zero, is not filled.

It looks like most compilers are going to initialize JAMP to zero for us, but since it's free, I would strongly recommend a
`          JAMP(:,:) = (0d0,0D0)`
before the JAMP lines. LO processes already have it, NLO processes should have it too. 

I'm reporting this issue because on my system even innocent-looking changes to the compilation flags or to the makefiles will prevent gfortran from initializing to zero, and then it's a big problem.

**Comment by marcozaro** [comment]
Thanks Claudio.
Just to be sure, jamp(2,2) is employed in the following?

**Comment by marcozaro** [comment]
> Thanks Claudio. Just to be sure, jamp(2,2) is employed in the following?

yes, it is, the loop is agnostic on the fact that there are 0-valued elements. I will fix this soon

**Comment by marcozaro** [comment]
2735d7c25
should contain the fix
