### ISSUE TITLE
condor refine.sh wrong path to madevent

### ISSUE THREAD

**Issue by APN-Pucky** [mg5amcnlo/mg5amcnlo#74]
Refine.sh uses the path `Ppath` to madevent

https://github.com/mg5amcnlo/mg5amcnlo/blob/c3a9c83a42d78e24cf989f4985fb551f8abec69c/Template/LO/SubProcesses/refine.sh#L70

it is defined here

https://github.com/mg5amcnlo/mg5amcnlo/blob/c3a9c83a42d78e24cf989f4985fb551f8abec69c/madgraph/madevent/gen_ximprove.py#L1459

but it is unsuitable for a condor setup without a nfs/shared file system. Instead using (hardcoded for my tests) `'Ppath':'..'` works as `madevent` is transmitted with the condor job as a input file

https://github.com/mg5amcnlo/mg5amcnlo/blob/c3a9c83a42d78e24cf989f4985fb551f8abec69c/madgraph/various/cluster.py#L971

Otherwise I get follwowing error 
![2023-11-24 14_49_29-a](https://github.com/mg5amcnlo/mg5amcnlo/assets/4533248/53ceeadb-e3ac-40c1-bb1e-2d3bc3e3c135)

Note that the first run (w/o refine) works without changing `Ppath`.

**Comment by APN-Pucky** [comment]
The advantage is that I can share dependencies like LHAPDF, pythia etc. over a small NFS and keep the large MG5 results on a local filesystem.

**Comment by oliviermattelaer** [comment]
Thanks, I will need to double check that this will not create issue for gridpack (and especially readonly gridpack) and if not then I could push the change.

**Comment by APN-Pucky** [comment]
I expect it to be problematic for other cases, but the stages before refine.sh did work, so maybe in refine.sh it could be done similar to the first `madevent` runs?

**Comment by oliviermattelaer** [comment]
Thanks,

I have update the code to follow your proposal (not yet pushed but will appear in 3.5.3 or 3.6.0 whoever appear first): 
https://github.com/mg5amcnlo/mg5amcnlo/commit/3e4b1795454f7b531ce592264f94427de18df43a

Thanks a lot for the suggestion/check

Olivier

**Comment by APN-Pucky** [comment]
Thanks!
