### ISSUE TITLE
install paths not being set

### ISSUE THREAD

**Issue by sihyunjeon** [mg5amcnlo/mg5amcnlo#86]
https://github.com/mg5amcnlo/HEPToolsInstallers/pull/5

while working on this,

i found out that fastjet and hepmc paths are not set although the compilations were successful, and thus

```
        set_env = set_env + "export LD_LIBRARY_PATH={0}:$LD_LIBRARY_PATH\n".format(pjoin(self.options['hepmc_path'], 'lib'))
        set_env = set_env + "export LD_LIBRARY_PATH={0}:$LD_LIBRARY_PATH\n".format(pjoin(self.options['fastjet'], 'lib'))
```

does not work as they are empty

let me know in which script the input paths are being set in mg5_configuration.txt

**Comment by oliviermattelaer** [comment]
normally they are set via the install command, where a 
save options command is set automatically

**Comment by sihyunjeon** [comment]
hi @oliviermattelaer fastjet is left empty after installation in mg5 3.5.3 as far as i can check. but i am not sure where this is handled in the script. if you let me know i can try to debug

**Comment by oliviermattelaer** [comment]
the branch 3.5.4 is now updated to fix that issue. Thanks @sihyunjeon

**Comment by sihyunjeon** [comment]
https://github.com/mg5amcnlo/mg5amcnlo/commit/bc3ef31f589fe57781c0e26fd20978ab2481e2c0

leaving notes
